/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistaEscritorio;

import Logica.Fachada;
import Logica.Gestor;
import Logica.Pedido;
import Logica.Servicio;
import Logica.UnidadProcesadora;
import controlador.ControladorGestor;
import controlador.VistaGestor;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import observador.EventoUnidad;
import observador.Observable;
import observador.Observador;

/**
 *
 * @author nicor
 */
public class VistaMenuGestorFrame extends javax.swing.JDialog implements VistaGestor {

    /**
     * Creates new form MenuGestor1
     */
    private Gestor gestor;
    private UnidadProcesadora unidad;
    private ControladorGestor controlador;
    private ArrayList<Pedido> pedidosP = new ArrayList<Pedido>();
    LocalDateTime ahora = LocalDateTime.now();

    public VistaMenuGestorFrame(java.awt.Frame parent, boolean modal, Gestor gestor, String Titulo) {
        super(parent, modal);
        initComponents();

        this.gestor = gestor;
        this.unidad = gestor.getuProc();

        setTitle("Unidad Procesadora " + gestor.getuProc() + " GESTOR " + gestor.getNombre().toUpperCase());
        controlador = new ControladorGestor(this, unidad);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaPedidos = new javax.swing.JList();
        btnTomarPedido = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaPedidos = new javax.swing.JTable();
        btnFinalizar = new javax.swing.JButton();
        btnEntregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pedidos");

        ListaPedidos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "No hay pedidos para mostrar" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ListaPedidos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaPedidosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListaPedidos);

        btnTomarPedido.setText("Tomar Pedido");
        btnTomarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomarPedidoActionPerformed(evt);
            }
        });

        TablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre Item", "Descripcion", "Cliente", "Fecha y Hora", "Estado"
            }
        ));
        jScrollPane2.setViewportView(TablaPedidos);

        btnFinalizar.setText("Finalizar Pedido");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        btnEntregar.setText("EntregarPedido");
        btnEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnFinalizar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEntregar))
                            .addComponent(btnTomarPedido, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 111, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTomarPedido)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEntregar)
                    .addComponent(btnFinalizar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTomarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomarPedidoActionPerformed
        // TODO add your handling code here:
        tomarPedido();
    }//GEN-LAST:event_btnTomarPedidoActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
        finalizarPedido();
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarActionPerformed
        entregarPedido();
    }//GEN-LAST:event_btnEntregarActionPerformed

    private void ListaPedidosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaPedidosValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaPedidosValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ListaPedidos;
    private javax.swing.JTable TablaPedidos;
    private javax.swing.JButton btnEntregar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnTomarPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void tomarPedido() {
        int pos = ListaPedidos.getSelectedIndex();
        if (pos != -1) {
            controlador.tomarPedido(pos);
            ListaPedidos.remove(pos);

        } else {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UN PEDIDO", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }

    @Override
    public void cargarListaPedidos(ArrayList<Pedido> pedidos) {
        
        //ArrayList<Pedido> pedidosConfirmados = unidad.getPedidosConfirmados();
        
        ArrayList<String> datos = new ArrayList<>();

        for (Pedido p : pedidos) {
            if (p.getEstadoPedido().equalsIgnoreCase("Confirmado")) {
                String estado = p.getEstadoPedido();
                String item = p.getItem().getNombre();
                String comentario = p.getComentario();
                String fechaHora = p.getFechayHora().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm"));
                String linea = item + " | Estado: " + estado + " | Comentario: " + comentario + " | Cliente: " + p.getServicio().getCliente() + " | Hora: " + fechaHora;
                datos.add(linea);
            }
        }

        ListaPedidos.setListData(datos.toArray(new String[0]));
    }

    @Override
    public void cargarTablaPedidosTomados(ArrayList<Pedido> pedidosTomados) {
        pedidosP = pedidosTomados;
        DefaultTableModel datos = new DefaultTableModel();

        datos.addColumn("Nombre Item");
        datos.addColumn("Descripcion");
        datos.addColumn("Cliente");
        datos.addColumn("Fecha y Hora");
        datos.addColumn("Estado");

        for (Pedido pedido : pedidosP) {
            pedido.setGestor(gestor);

            String fechaHora = pedido.getFechayHora().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm"));
            Object[] fila = {
                pedido.getItem(),
                pedido.getComentario(),
                pedido.getServicio().getCliente(),
                fechaHora,
                pedido.getEstadoPedido()
            };
            datos.addRow(fila);
        }

        TablaPedidos.setModel(datos);
    }

    private void finalizarPedido() {

        int pos = TablaPedidos.getSelectedRow();        
            
            try{
                controlador.finalizarPedido(pos);
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }            

        
    }

    private void entregarPedido() {
        int pos = TablaPedidos.getSelectedRow();
       
            try{
                controlador.entregarPedido(pos);
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            
    }

}
